### ISSUE TITLE
Issue/Ticket Format

### ISSUE THREAD

**Issue by boomboompower** [boomboompower/SimpleChatAlert#1]
Hello! If you are here, it means one of two things, either you clicked the wrong button (In which case [click here](dev.bukkit.org/bukkit-plugins/simple-chat-alert) to return to the bukkit page) or you are here to _Report a bug!_ yay!

If you are going to report an issue with the plugin, please follow this format so it is easier for us to fix your error! Check out [this page](https://github.com/boomboompower/SimpleChatAlert/wiki/Commands-And-Uses) to view some commands that *may* be helpful!

**Server Version:**

**Running:**

**NMS Version:**

**Plugin Version:**

**Error in console:**

**Comment by gogobebe2** [comment]
cool :+1:

**Comment by boomboompower** [comment]
xD Im still editing it
